#!/bin/bash
#
#
if dpkg-query -W -f='${Status}' apache2 2>/dev/null | grep -c "ok installed" ; then
# leiab kas on olemas sõnad ok installed , kui on, siis apache2 ei installi
	echo "apache2 is already installed"
	systemctl status apache2
# kui apache2 ei ole installitud, siis installib
	else
	echo "installing apache2"
	apt install apache2 -y
fi
