#!/bin/bash
#
# Kustutab kõik ära
apt purge mysql-server apache2 php7.0 libapache2-mod-php7.0 php7.0-mysql php7.0-curl php7.0-json php7.0-cgi -y && apt-get autoremove -y
echo =======================================================================================================
systemctl status apache2
echo =======================================================================================================
systemctl status mysql
