#!/bin/bash
#
#
if apt install php | grep -c "0 newly installed" ; then
# leiab kas on olemas sõnad ok installed , kui on, siis apache2 ei installi
	echo -e "PHP is already installed!"
# kui apache2 ei ole installitud, siis installib
	else
	echo -n "installing PHP"
	apt install php7.0 libapache2-mod-php7.0 php7.0-mysql php7.0-curl php7.0-json php7.0-cgi -y
fi
