#!/bin/bash
#
#
if apt install php7.0 libapache2-mod-php7.0 php7.0-mysql php7.0-curl php7.0-json php7.0-cgi -y | grep -c "newest version" ; then
# leiab kas on olemas sõna [Y/n] , kui on, siis installib php
        echo "PHP is already installed"
# kui php on installitud, siis ei installib
fi
