#!/bin/bash
#
if apt install php7.0 libapache2-mod-php7.0 php7.0-mysql php7.0-curl php7.0-json php7.0-cgi -y | grep -c "newest version" ; then
# hakkab phpd installima, kui php on juba installitud siis ütleb et PHP is already installed
        echo "PHP is already installed"
fi
