#!/bin/bash
#
# kontrollib kas kõik on olemas
sh apache_install
sh php_install
sh mysql_install
sh phpmyadmin_install
# läheb html kausta ja installib wordpressi
cd /var/www/html
wget -c https://wordpress.org/latest.tar.gz
tar -xzvf latest.tar.gz
# võtab html kaustast index.htmli ära et wordpress töötaks
mv index.html ..
mv wordpress/* .
rm -rf wordpress/
rm -rf latest.tar.gz
